Fix brsc and suppress warnings
MediaTek-Labs/llvm-project pull request #16
Opened 2023-07-06 09:17 UTC by milica-lazarevic

Added isBarier flag to definition of BRSC_NM.

Suppressed warnings during build:
 - Reordered NanoMipsJumpTableInfo constructor parameters.
 - Added override identifier to use useIPRA.

2023-07-06 13:28 UTC, djtodoro commented
This fixes an assertion (regarding the `BRSC_NM`) when building `lllvm-test-suite` for `nanoMips`.

2023-07-07 04:20 UTC, draganmladjenovic approved these changes

2023-07-07 10:30 UTC, djtodoro commented
@milica-lazarevic should be created against `nanomips` branch (from now on).

2023-07-09 07:15 UTC, farazs-github requested changes
This PR contains a lot of duplicate changes from PR #10

2023-07-09 14:07 UTC, djtodoro commented
> This PR contains a lot of duplicate changes from PR #10

Yes, but the PR was not merged with the `nanomips`, which is the main dev branch as of now.

2023-07-10 15:29 UTC, farazs-github approved these changes
LGTM

2023-07-14 14:40 UTC, cme approved these changes
Thanks!

2023-07-14 14:40 UTC, cme commented on llvm/lib/Target/Mips/MipsTargetMachine.h
> +  bool useIPRA() const override {
Thanks, I have kept meaning to do this for a *very* long time :D

2023-07-14 14:40 UTC, merged