NanoMips: div-rem optimization
MediaTek-Labs/llvm-project pull request #2
Opened 2022-12-15 12:07 UTC by nikolaperic

Disable expansion of mod to mul-and-sub when Os or Oz. Generate udivmoddi4 libcall when div-rem pairs of type uint64 are present.

This resolves the following issue:
```
- LLVM uses multiplication for divmod pattern
  - Find where the expansion of mod to multiply-and-subtract is done and disable when -Os

```

2023-03-14 18:33 UTC, draganmladjenovic requested changes

2023-03-14 18:33 UTC, draganmladjenovic commented on llvm/lib/Target/Mips/NanoMipsTargetTransformInfo.cpp
> +  return F->hasOptSize();
Do we want this for i64 even when optimizing for speed? I think we should at least for unsigned types due to libcall limitation.

2023-03-14 18:33 UTC, draganmladjenovic commented on llvm/lib/Target/Mips/MipsSEISelLowering.cpp
> +      ShiftAmountTy = MVT::getIntegerVT(NextPowerOf2(ReqShiftAmountInBits));
Not sure if we really need to guard this case. You might just assert on it.

2023-03-16 09:59 UTC, cme commented on llvm/lib/Target/Mips/MipsSEISelLowering.cpp
> +  unsigned Opcode = Op.getOpcode();
Since it's an odd ABI to this call, I think it warrants some commentary to explain the ABI used and the rationale.

2023-03-22 12:07 UTC, djtodoro commented
@nikolaperic Please set the target branch to `nanomips-llvm13-submission`.

2023-03-22 12:16 UTC, draganmladjenovic approved these changes

2023-03-27 09:49 UTC, merged