llvm-objcopy: Disable huge sec offset
MediaTek-Labs/llvm-project pull request #49
Opened 2024-09-06 10:41 UTC by djtodoro

Match GNU objcopy's behavior.
This is controlled by an option, that is set to OFF by default.

2024-09-06 12:29 UTC, farazs-github requested changes
Review comments

2024-09-06 12:29 UTC, farazs-github commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +        int FilePosition = Sec.Offset;
Since Sec.Offset is already 64-bit, I think it would be clearer to just compare against the maximum offset we want to allow instead of type-casting to int for overflow.

2024-09-06 12:29 UTC, farazs-github commented on llvm/include/llvm/ObjCopy/ELF/ELFConfig.h
> +  bool DisableHugeSectionOffset = false;
1. Flag with Disable in the name and set to false (double negative) makes code harder to read.
2. Allow/Disallow makes more sense, than Enable/Disable where we're flagging an error.
So I suggest using AllowHugeSectionOffset here.

2024-09-06 12:29 UTC, farazs-github commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +      // More or less, this makes sense to do for 32-bit targets.
I disagree. 
1. The problem(of producing a large binary dump) is one of physical memory, not address space.
2. We're not even maxing out on available 32-bit space, so the check is independent of address space in that regard.

2024-09-06 12:29 UTC, farazs-github commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +                                       " at huge (ie negative) file offset");
In conjunction with the previous comment, you can drop the (ie negative). We don't have to match the exact error of GNU objcopy. It does not make sense here (nor in binutils for that matter).

2024-09-07 10:00 UTC, djtodoro commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +                                       " at huge (ie negative) file offset");
Yep, I agree.

2024-09-07 10:03 UTC, djtodoro commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +      // More or less, this makes sense to do for 32-bit targets.
Well... now when I think about it, you are right. I wanted to express that it is harder to reproduce this on 64-bit targets (and to be more conservative with the respect to the feature itself), but it is not relevant at all. I will delete this comment and remove the restriction.

2024-09-07 11:14 UTC, djtodoro commented on llvm/lib/ObjCopy/ELF/ELFObject.cpp
> +        int FilePosition = Sec.Offset;
Yep, great, lets to that way. Thanks!

2024-09-07 11:16 UTC, djtodoro commented
@farazs-github Thanks for the feedback!

2024-09-11 10:27 UTC, djtodoro commented
I've gotten some comments on the upstream PR. I will apply them here when it is ready/merged there.

2024-09-16 13:49 UTC, djtodoro commented
I have incorporated all comments from reviewers from the upstream PR. They are happy with implementation, but there is ongoing discussion about the option being accepted at first place.

2024-09-28 18:13 UTC, djtodoro commented
Merged internally (review process also done on upstream - the implementation is OK, but there is a discussion if we even want this option in mainline).

2024-09-28 18:13 UTC, closed without merging